// src/views/Home.vue
﻿<template>
	<div
		class="home flex flex-wrap pt-16 md:pt-p2 h-screen w-screen overflow-x-hidden overflow-y-auto"
	>
		<!--Left side input panel-->
		<div
			class="w-2/4 p-p1 flex-basis-like-1/1 grow md:flex-1 bg-bg1 text-left pt-p1 pl-p3 pr-p3 flex flex-col"
		>
			<p role="heading" aria-level="1" class="text-2xl md:text-3xl">
				{{ $t("default.editContent") }}
			</p>
			<div class="mt-8 md:mt-m1 flex justify-end items-center mb-m2">
				<button class="home-btn" @click="insertMark">
					{{ $t("default.mark") }}
				</button>
				<button class="home-btn" @click="LaTeXSepConvert('d2b')">
					{{ $t("default.dollar2bracket") }}
				</button>
				<button class="home-btn" @click="LaTeXSepConvert('b2d')">
					{{ $t("default.bracket2dollar") }}
				</button>
				<button class="home-btn" @click="importClick">
					{{ $t("default.import") }}
				</button>
				<button class="home-btn" @click="exportClick">
					{{ $t("default.export") }}
				</button>
				<button
					class="hover:scale-110 transition-scale"
					@click="showUseTipModal = true"
					:aria-label="$t('default.descript')"
				>
					<SvgIcon
						name="question-circle"
						:size="34"
						color="#313746"
						class="cursor-pointer"
					/>
				</button>
			</div>
			<EditIconsTab @insert-latex="insertLatex" />
			<div class="flex flex-1">
				<textarea
					v-if="basic === true"
					class="left-side-input-textarea flex-1 resize-none p-3 border border-bd1 overflow-y-scroll rounded-b-lg"
					ref="inputArea"
					type="text"
					v-model="data"
				/>
				<div
					v-else
					id="codemirror"
					class="left-side-input-textarea flex-1 resize-none border border-bd1 overflow-y-scroll rounded-b-lg"
				></div>
				<input
					type="file"
					ref="importFile"
					class="hidden"
					@change="importAction"
				/>
			</div>
		</div>
		<!--Right side output panel-->
		<div
			class="w-2/4 flex-basis-like-1/1 grow md:flex-1 text-left p-p1 pt-p1 pl-p3 flex flex-col"
		>
			<div class="flex md:mb-m3 w-100">
				<p role="heading" aria-level="1" class="text-2xl md:text-3xl w-100">
					{{ $t("default.result") }}
				</p>
				<button
					@click="showSettingModal = true"
					:aria-label="$t('default.useSetting')"
				>
					<SvgIcon
						name="settings"
						:size="34"
						color="#313746"
						class="cursor-pointer"
					/>
				</button>
			</div>
			<template v-if="selecteds['HTML_document_display'] === 'markdown'">
				<div
					v-html="contentmd"
					class="right-side-input-textarea border-2 overflow-scroll p-4 flex-1 rounded-lg"
				/>
			</template>
			<template v-else>
				<div
					class="right-side-input-textarea border-2 overflow-scroll p-4 flex-1 rounded-lg"
				>
					<template v-for="(line, key) in content" :key="key">
						<span><span v-html="line" /></span><br />
					</template>
				</div>
			</template>
		</div>
		<Modal v-if="showUseTipModal" @close="showUseTipModal = false">
			<template v-slot:header>
				<div class="text-4xl font-bold">{{ $t("default.useDescript") }}</div>
			</template>
			<template v-slot:body>
				<div class="mt-m2">
					<div
						v-for="(tip, k) in useTip[$i18n.locale]"
						:key="k"
						class="py-p5 px-m2 text-left text-lg"
					>
						<b>{{ tip.title }}</b>
						<p>{{ tip.content }}</p>
					</div>
				</div>
			</template>
			<template v-slot:footer>
				<button class="btn-style_1" @click="showUseTipModal = false">
					{{ $t("default.understand") }}
				</button>
			</template>
		</Modal>
		<Modal v-if="showSettingModal" @close="showSettingModal = false">
			<template v-slot:header>
				<div class="text-4xl font-bold">{{ $t("default.useSetting") }}</div>
			</template>
			<template v-slot:body>
				<div class="mt-m2">
					<div
						v-for="(setting, id) in settings[$i18n.locale]"
						:key="id"
						class="py-2 px-m2 text-left text-lg"
					>
						<div>
							<b>{{ setting.name }}</b>
						</div>
						<div
							class="py-1 pr-4 inline-block"
							v-for="(option, o) in setting.options"
							:key="o"
						>
							<input
								:id="option.value"
								type="radio"
								:value="option.value"
								v-model="selecteds[id]"
								:name="id"
							/>
							<label :for="option.value">{{ option.display }}</label>
						</div>
					</div>
				</div>
			</template>
			<template v-slot:footer>
				<button class="btn-style_1" @click="showSettingModal = false">
					{{ $t("default.SettingFinish") }}
				</button>
			</template>
		</Modal>
	</div>
</template>

<script setup>
import { ref, computed, onUpdated, onMounted } from "vue"; //new add
import { marked as markedFactory } from "@/utils/lib/markdownProcess.js";
import { textmath2laObj as textmath2laObjFactory } from "@/utils/lib/mathProcess.js";
import asciimath2mmlFactory from "@/utils/lib/am2mml.js";
import latex2mmlFactory from "@/utils/lib/tex2mml.js";
import mml2svg from "@/utils/lib/mml2svg.js";
import { getFileDataAsText } from "@/utils/utils";
import { useTip } from "../utils/tips";
import settings from "../utils/setting";
import EditIconsTab from "@/components/EditIconsTab.vue";
import Modal from "../components/Modal.vue";
import { basicSetup } from "codemirror";
import { EditorView } from "@codemirror/view";
import { EditorState, EditorSelection } from "@codemirror/state";
import { markdown } from "@codemirror/lang-markdown";
import { autocompletion } from "@codemirror/autocomplete";
import latexs from "../utils/latexs";

const basic = false;
const selecteds = ref({
	HTML_document_display: "markdown",
	HTML_math_display: "block",
	color_match: "blackTextOnWhiteBackground",
	LaTeX_delimiter: "bracket",
});
const selectionStart = ref(-1);
const selectionEnd = ref(-1);
const showUseTipModal = ref(false);
const showSettingModal = ref(false);
const inputArea = ref(null);
const importFile = ref(null);
const codemirrorView = ref(null); //new add
const data = ref("");
const content = computed(() => {
	return data.value.split("\n").map((line) => {
		return textmath2laObjFactory({
			latex_delimiter: selecteds.value["LaTeX_delimiter"],
			asciimath_delimiter: "graveaccent",
		})(line).reduce((a, b) => {
			let result;
			if (b.type === "latex-content") {
				result = `<div class="sr-only">${latex2mmlFactory({
					display: selecteds.value["HTML_math_display"],
				})(b.data)}</div><div aria-hidden="true">${mml2svg(
					latex2mmlFactory({
						display: selecteds.value["HTML_math_display"],
					})(b.data)
				)}</div>`;
			} else if (b.type === "asciimath-content") {
				result = `<div class="sr-only">${asciimath2mmlFactory({
					display: selecteds.value["HTML_math_display"],
				})(b.data)}</div><div aria-hidden="true">${mml2svg(
					asciimath2mmlFactory({
						display: selecteds.value["HTML_math_display"],
					})(b.data)
				)}</div>`;
			} else {
				result = `${b.data}`;
			}
			return a + result;
		}, "");
	});
});
const contentmd = computed(() => {
	return markedFactory({
		latex_delimiter: selecteds.value["LaTeX_delimiter"],
		asciimath_delimiter: "graveaccent",
		display: selecteds.value["HTML_math_display"],
	})(data.value);
});
const bdconvert = (mode) => (data) => {
	return data
		.split("\n")
		.map((line) => {
			let latex_delimiter = "dollar";
			if (mode === "b2d") {
				latex_delimiter = "bracket";
			} else if (mode === "d2b") {
				latex_delimiter = "dollar";
			}
			return textmath2laObjFactory({
				latex_delimiter,
				asciimath_delimiter: "graveaccent",
			})(line).reduce((a, b) => {
				let result;
				if (b.type === "latex-content") {
					if (mode === "b2d") {
						result = `$${b.data}$`;
					} else if (mode === "d2b") {
						result = `\\(${b.data}\\)`;
					} else {
						result = `\\(${b.data}\\)`;
					}
				} else if (b.type === "asciimath-content") {
					result = `\`${b.data}\``;
				} else {
					result = `${b.data}`;
				}
				return a + result;
			}, "");
		})
		.reduce((a, b) => {
			return a + b + "\n";
		}, "");
};
// new add
let insertMark;
let insertLatex;
let importAction;
let LaTeXSepConvert;
if (basic) {
	insertMark = () => {
		const target = inputArea.value;
		const selectedText = target.value.slice(
			target.selectionStart,
			target.selectionEnd
		);
		let LaTeX_delimiter_start = "\\(";
		let LaTeX_delimiter_end = "\\)";
		if (selecteds.value["LaTeX_delimiter"] === "bracket") {
			LaTeX_delimiter_start = "\\(";
			LaTeX_delimiter_end = "\\)";
		} else if (selecteds.value["LaTeX_delimiter"] === "dollar") {
			LaTeX_delimiter_start = "$";
			LaTeX_delimiter_end = "$";
		}
		const startOffset = LaTeX_delimiter_start.length;
		const endOffset = LaTeX_delimiter_end.length;
		const content = `${LaTeX_delimiter_start}${selectedText}${LaTeX_delimiter_end}`;
		data.value =
			data.value.slice(0, target.selectionStart) +
			content +
			data.value.slice(target.selectionEnd, data.value.length);
		selectionStart.value = target.selectionStart + startOffset;
		selectionEnd.value = target.selectionEnd + endOffset;
	};
	insertLatex = (e) => {
		const { latex, offset } = e;
		const target = inputArea.value;
		const content = latex;
		data.value =
			data.value.slice(0, target.selectionStart) +
			content +
			data.value.slice(target.selectionEnd, data.value.length);
		selectionStart.value = target.selectionStart + latex.length + offset;
		selectionEnd.value = target.selectionStart + latex.length + offset;
	};
	importAction = async (e) => {
		try {
			const file = e.target.files[0];
			data.value = await getFileDataAsText(file);
		} catch (err) {
			console.log(err);
		}
	};
	LaTeXSepConvert = (mode) => {
		data.value = bdconvert(mode)(data.value);
	};
} else {
	insertMark = () => {
		let LaTeX_delimiter_start = "\\(";
		let LaTeX_delimiter_end = "\\)";
		if (selecteds.value["LaTeX_delimiter"] === "bracket") {
			LaTeX_delimiter_start = "\\(";
			LaTeX_delimiter_end = "\\)";
		} else if (selecteds.value["LaTeX_delimiter"] === "dollar") {
			LaTeX_delimiter_start = "$";
			LaTeX_delimiter_end = "$";
		}
		const startOffset = LaTeX_delimiter_start.length;
		const endOffset = LaTeX_delimiter_end.length;
		const view = codemirrorView.value;
		view.dispatch(
			view.state.changeByRange((range) => {
				return {
					changes: [
						{ from: range.from, insert: LaTeX_delimiter_start },
						{ from: range.to, insert: LaTeX_delimiter_end },
					],
					range: EditorSelection.range(
						range.from + startOffset,
						range.to + endOffset
					),
				};
			})
		);
		view.focus();
	};
	insertLatex = (e) => {
		const { latex, offset } = e;
		const view = codemirrorView.value;
		view.dispatch(
			view.state.changeByRange((range) => ({
				changes: [
					{
						from: range.from,
						insert: latex.slice(0, latex.length + offset),
					},
					{
						from: range.to,
						insert: latex.slice(latex.length + offset, latex.length),
					},
				],
				range: EditorSelection.range(
					range.from + latex.length + offset,
					range.from + latex.length + offset
				),
			}))
		);
		view.focus();
	};
	importAction = async (e) => {
		try {
			const file = e.target.files[0];
			data.value = await getFileDataAsText(file);
			createView(data.value);
		} catch (err) {
			console.log(err);
		}
	};
	LaTeXSepConvert = (mode) => {
		const value = bdconvert(mode)(data.value);
		createView(value);
	};
}
// new add
const importClick = () => {
	importFile.value.click();
};
const exportClick = () => {
	const output = data.value;
	const url = window.URL.createObjectURL(new Blob([output]));
	const link = document.createElement("a");
	link.href = url;
	link.setAttribute("download", "export.txt");
	document.body.appendChild(link);
	link.click();
};
onUpdated(() => {
	if (selectionStart.value >= 0 && selectionEnd.value >= 0) {
		const target = inputArea.value;
		target.setSelectionRange(selectionStart.value, selectionEnd.value);
		target.focus();
		selectionStart.value = -1;
		selectionEnd.value = -1;
	}
});
onMounted(() => {
	createView();
});
const myCompletions = (context) => {
	let word = context.matchBefore(new RegExp("\\\\\\w*"));
	if (!word || (word.from == word.to && !context.explicit)) return null;
	const options = latexs.map((item) => {
		return {
			label: item.latex,
			type: "text",
			apply: item.latex,
		};
	});
	return {
		from: word.from,
		options,
	};
};
const createView = (content = "") => {
	if (codemirrorView.value) {
		codemirrorView.value.destroy();
	}
	const editorView = EditorView.theme({
		"&": {
			fontSize: "16px",
			backgroundColor: "white",
			minHeight: "300px",
			height: "100%",
		},
		".cm-scroller": { overflow: "auto" },
	});
	codemirrorView.value = new EditorView({
		state: EditorState.create({
			doc: content,
			extensions: [
				basicSetup,
				autocompletion({
					override: [myCompletions],
				}),
				markdown(),
				EditorView.updateListener.of((update) => {
					data.value = update.view.state.doc.toString();
				}),
				editorView,
				EditorView.lineWrapping,
			],
		}),
		parent: document.getElementById("codemirror"),
	});
};
</script>
<style scoped lang="scss">
.left-side-input-textarea,
.right-side-input-textarea {
	min-height: 300px;
}

// .right-side-input-textarea {
// 	vertical-align: middle;
// }
.right-side-input-textarea {
	:deep(> *) {
		// display: inline-block;
		margin: var(--spacing-2-5) var(--spacing-5);
		vertical-align: middle;
	}

	:deep(ol) {
		list-style-type: decimal;
	}

	:deep(ul) {
		list-style-type: disc;
	}

	:deep(table) {
		border: 1px solid black;
		tr {
			border: inherit;
		}
		td,
		th {
			@apply p-1;
			border: 1px solid black;
		}
	}

	:deep(svg) {
		@apply inline-block;
	}
}
</style>

// src/pages/home/home.jsx
'use client';

import React, { useState, useMemo, useCallback, useRef, useEffect } from 'react';
import { basicSetup } from 'codemirror';
import { EditorView } from '@codemirror/view';
import { EditorState, EditorSelection } from '@codemirror/state';
import { markdown } from '@codemirror/lang-markdown';
import { autocompletion } from '@codemirror/autocomplete';

import { asConfigData } from '@/lib/config/data';

import { useTranslation } from '@/lib/i18n';
import {
  getFileDataAsText,
  parseA8MWFile,
  saveContentAsWebsite,
  saveContentAsOriginalFile,
  ORIGINAL_FILE_EXTENSION,
} from '@/lib/file';
import autoCompletions from '@/lib/editor-auto-completion';

import { latexDelimiterConvertor } from '@coseeing/see-mark';

import Header from '@/components/header';
import { IconChevronDown } from '@tabler/icons-react';
import Button from '@/components/core/button';
import DropdownMenu from '@/components/core/dropdown-menu';
import SegmentedControl from '@/components/core/button/segmented-control';
import EditIconsTab from '@/components/edit-icons-tab';
import SettingModal from '@/components/home/setting-modal';
import ConvertHintModal from '@/components/home/convert-hint-modal';
import { useDisplayConfig, ExportType, LatexDelimiter, DocumentColor } from '@/lib/display-config';
import { importSource } from '@/lib/import-source';

import useSeeMarkParse from './useSeeMarkParse';

const importTextAcceptedExtension = ['.txt', '.md'];
const importAcceptedExtension = [`.${ORIGINAL_FILE_EXTENSION}`];

export default function Home() {
  const t = useTranslation('home');
  const [data, setData] = useState('');
  const [showSettingModal, setShowSettingModal] = useState(false);
  const [showConvertHintModal, setShowConvertHintModal] = useState(false);
  const [exportType, setExportType] = useState(ExportType.ZIP);
  const [imageFiles, setImageFiles] = useState({});

  const { displayConfig, setDisplayConfig } = useDisplayConfig();

  const codemirrorView = useRef(null);
  const importFile = useRef(null);
  const imagesToExportRef = useRef({});

  const addImageToExport = useCallback((fileID, fileType, file) => {
    const fileName = `${fileID}.${fileType}`;
    imagesToExportRef.current = {
      ...imagesToExportRef.current,
      [fileID]: { file, fileName },
    };
    setImageFiles((prevFiles) => ({
      ...prevFiles,
      [fileID]: file,
    }));
  }, []);

  const seeMarkReactParse = useSeeMarkParse({
    latexDelimiter: displayConfig.latexDelimiter,
    documentFormat: displayConfig.documentFormat,
    imageFiles,
  });

  const content = useMemo(() => {
    return seeMarkReactParse(data);
  }, [data, seeMarkReactParse]);

  const createView = useCallback((content = '') => {
    if (codemirrorView.current) {
      codemirrorView.current.destroy();
    }
    const editorView = EditorView.theme({
      '&': {
        fontSize: '16px',
        backgroundColor: 'white',
        minHeight: '300px',
        height: '100%',
      },
      '.cm-scroller': {
        overflow: 'auto',
        lineHeight: '1.5',
      },
      '.cm-gutters': {
        backgroundColor: '#fff',
        border: 'none',
        borderRight: '1px solid #d1d1d1',
      },
      '.cm-lineNumbers .cm-gutterElement': {
        width: '42px',
        minWidth: '42px',
        padding: '8px',
        color: '#6d6d6d',
        fontSize: '16px',
        lineHeight: '1.5',
        textAlign: 'center',
      },
      '.cm-lineNumbers .cm-gutterElement:first-of-type': {
        padding: 0,
      },
      '.cm-foldGutter .cm-gutterElement': {
        lineHeight: '2.5',
      },
      '.cm-content': {
        color: '#454545',
        padding: 0,
      },
      '.cm-line': {
        padding: '8px',
      },
    });
    codemirrorView.current = new EditorView({
      state: EditorState.create({
        doc: content,
        extensions: [
          basicSetup,
          autocompletion({
            override: [autoCompletions],
          }),
          markdown(),
          EditorView.updateListener.of((update) => {
            setData(update.view.state.doc.toString());
          }),
          editorView,
          EditorView.lineWrapping,
        ],
      }),
      parent: document.getElementById('codemirror'),
    });
  }, []);

  useEffect(() => {
    createView();
    // Adjust selection after creating the view
    if (codemirrorView.current) {
      adjustSelection(codemirrorView.current);
    }
  }, [createView]);

  const insertMark = useCallback(() => {
    let LaTeX_delimiter_start = '\\(';
    let LaTeX_delimiter_end = '\\)';
    if (displayConfig.latexDelimiter === LatexDelimiter.BRACKET) {
      LaTeX_delimiter_start = '\\(';
      LaTeX_delimiter_end = '\\)';
    } else if (displayConfig.latexDelimiter === LatexDelimiter.DOLLAR) {
      LaTeX_delimiter_start = '$';
      LaTeX_delimiter_end = '$';
    }
    const startOffset = LaTeX_delimiter_start.length;
    const endOffset = LaTeX_delimiter_end.length;
    const view = codemirrorView.current;
    view.dispatch(
      view.state.changeByRange((range) => {
        return {
          changes: [
            {
              from: range.from,
              insert: LaTeX_delimiter_start,
            },
            {
              from: range.to,
              insert: LaTeX_delimiter_end,
            },
          ],
          range: EditorSelection.range(range.from + startOffset, range.to + endOffset),
        };
      })
    );
    view.focus();
  }, [displayConfig]);

  const laTeXSepConvert = useCallback(
    (mode) => {
      const value = latexDelimiterConvertor(mode)(data);
      createView(value);
    },
    [data, createView]
  );

  const importClick = useCallback(() => {
    importFile.current.click();
  }, []);

  const insertLatex = useCallback(({ id, latex, offset }) => {
    const view = codemirrorView.current;
    view.dispatch(
      view.state.changeByRange((range) => {
        // If it's a heading, insert at the start of the line
        if (id?.startsWith('heading')) {
          const line = view.state.doc.lineAt(range.from);
          return {
            changes: [
              {
                from: line.from,
                insert: latex,
              },
            ],
            range: EditorSelection.range(range.from + latex.length, range.to + latex.length),
          };
        }

        return {
          changes: [
            {
              from: range.from,
              insert: latex.slice(0, latex.length + offset),
            },
            {
              from: range.to,
              insert: latex.slice(latex.length + offset, latex.length),
            },
          ],
          range: EditorSelection.range(
            range.from + latex.length + offset,
            range.from + latex.length + offset
          ),
        };
      })
    );
    view.focus();
  }, []);

  const importFileAction = useCallback(
    async (event) => {
      const file = event.target.files[0];
      if (!file) {
        console.log('file not found');
        return;
      }
      const fileName = file.name;
      const fileExtension = fileName.substring(fileName.lastIndexOf('.')).toLowerCase();
      try {
        if (importAcceptedExtension.includes(fileExtension)) {
          const { config, text, imagesFolder } = await parseA8MWFile(file);
          return importSource(
            text,
            config,
            imagesFolder,
            addImageToExport,
            setImageFiles,
            setDisplayConfig,
            createView,
            displayConfig
          );
        }

        if (importTextAcceptedExtension.includes(fileExtension)) {
          const newData = await getFileDataAsText(file);
          return importSource(
            newData,
            {},
            null,
            addImageToExport,
            setImageFiles,
            setDisplayConfig,
            createView,
            displayConfig
          );
        }
      } catch (error) {
        // TODO: implement global alert or notification to handle the error
        console.error(error);
      } finally {
        event.target.value = null;
      }
    },
    [createView, displayConfig, setDisplayConfig, addImageToExport]
  );

  const exportFileAction = useCallback(
    (updatedConfig, exportType, fileName) => {
      setDisplayConfig(updatedConfig);
      // FIXME: get back the cleaning feature
      const cleanedImages = imagesToExportRef.current;

      switch (exportType) {
        case ExportType.ZIP:
          saveContentAsWebsite(data, asConfigData(updatedConfig), cleanedImages, fileName);
          break;
        case ExportType.A8M:
          saveContentAsOriginalFile(data, asConfigData(updatedConfig), cleanedImages, fileName);
          break;
        default:
          console.error('Unsupported export type');
      }
    },
    [data, setDisplayConfig]
  );

  const latexDelimiterOptions = [
    { id: LatexDelimiter.DOLLAR, label: t('latexDelimiter.dollar') },
    { id: LatexDelimiter.BRACKET, label: t('latexDelimiter.bracket') },
  ];

  function adjustSelection(view) {
    const state = view.state;
    const doc = state.doc;
    const cursor = view.state.selection.main.head;

    // Check if the cursor is outside the document
    if (cursor > doc.length) {
      // Set the cursor to the end of the document
      view.dispatch({
        selection: EditorSelection.cursor(doc.length),
      });
    }
  }

  return (
    <div className="flex flex-col lg:h-screen lg:overflow-hidden">
      <Header
        onImportClick={importClick}
        onExportClick={() => setShowSettingModal(true)}
        title={displayConfig.title}
        onTitleChange={(title) => setDisplayConfig({ title })}
      />
      <main className="min-w-[768px] flex flex-col lg:flex-row lg:flex-1 lg:min-h-0 lg:overflow-hidden">
        {/* Left side input panel */}
        <div className="lg:w-3/5 bg-blue-50 p-6 flex flex-col lg:h-full min-h-0">
          <div className="flex items-center justify-between mb-4">
            <h2>{t('editContent')}</h2>
            <div className="flex items-center gap-2">
              <div className="flex items-center">
                <div
                  id="latex-delimiter-label"
                  className="mr-2 text-text-primary text-sm font-medium"
                >
                  {t('latexDelimiter.name')}
                </div>
                <SegmentedControl
                  aria-labelledby="latex-delimiter-label"
                  items={latexDelimiterOptions}
                  value={displayConfig.latexDelimiter}
                  onChange={(option) => setDisplayConfig({ latexDelimiter: option })}
                  buttonClassName="w-16 h-7"
                />
              </div>
              <Button variant="secondary" onClick={insertMark}>
                {t('insert')}{' '}
                {displayConfig.latexDelimiter === LatexDelimiter.DOLLAR ? '$' : '\\( \\)'}{' '}
                {t('mark')}
              </Button>
              <Button
                variant="secondary"
                onClick={() => {
                  setShowConvertHintModal(true);
                }}
              >
                {displayConfig.latexDelimiter === LatexDelimiter.DOLLAR
                  ? t('dollar2bracket')
                  : t('bracket2dollar')}
              </Button>
            </div>
          </div>

          <div className="flex h-[600px] lg:h-auto lg:flex-1 min-h-0 border border-border-main bg-white rounded-lg overflow-hidden">
            <div className="w-1/3 flex-shrink-0 h-full">
              <EditIconsTab insertLatex={insertLatex} addImageToExport={addImageToExport} />
            </div>
            <div className="w-2/3 h-full">
              <div
                id="codemirror"
                className="h-full left-side-input-textarea flex-1 resize-none overflow-y-scroll"
              />
              <input
                ref={importFile}
                accept={[...importTextAcceptedExtension, ...importAcceptedExtension].join(', ')}
                type="file"
                className="hidden"
                onChange={importFileAction}
              />
            </div>
          </div>
        </div>

        {/* Right side output panel */}
        <div className="lg:w-2/5 flex flex-col p-6 lg:h-full min-h-0">
          <div className="flex justify-between items-center mb-4">
            <h2>{t('preview')}</h2>
            <div>
              <DropdownMenu
                align="right"
                triggerButton={
                  <Button variant="secondary" className="gap-2">
                    <span>
                      {displayConfig.documentColor === DocumentColor.DARK
                        ? t('documentColor.dark')
                        : t('documentColor.light')}
                    </span>
                    <IconChevronDown size={16} aria-hidden="true" />
                  </Button>
                }
                items={[
                  {
                    label: t('documentColor.light'),
                    onClick: () => setDisplayConfig({ documentColor: DocumentColor.LIGHT }),
                  },
                  {
                    label: t('documentColor.dark'),
                    onClick: () => setDisplayConfig({ documentColor: DocumentColor.DARK }),
                  },
                ]}
                itemsClassName="min-w-[118px]"
              />
            </div>
          </div>
          {/* `relative` makes this the containing block for the absolutely-positioned
              `.sr-only` MathML spans see-mark emits, so they're clipped here instead of
              resolving against the viewport and adding phantom page scroll. */}
          <div
            className={`right-side-preview-area relative border border-border-main leading-[1.5] space-y-3 p-4 h-[600px] lg:h-auto lg:flex-1 min-h-0 overflow-y-auto rounded-lg ${
              displayConfig.documentColor === DocumentColor.DARK
                ? 'darkmode bg-gray-800 text-white'
                : 'bg-white text-text-primary'
            }`}
          >
            {content}
          </div>
        </div>

        <SettingModal
          isOpen={showSettingModal}
          onClose={() => setShowSettingModal(false)}
          onSubmit={exportFileAction}
          displayConfig={displayConfig}
          exportType={exportType}
          setExportType={setExportType}
        />
        <ConvertHintModal
          isOpen={showConvertHintModal}
          onClose={() => setShowConvertHintModal(false)}
          displayConfig={displayConfig}
          setDisplayConfig={setDisplayConfig}
          laTeXSepConvert={laTeXSepConvert}
          LatexDelimiter={LatexDelimiter}
          data={data}
        />
      </main>
    </div>
  );
}
